### ISSUE TITLE
Question about FHT implementation for CUL

### ISSUE THREAD

**Issue by Elwetana** [timroemisch/mqtt-s7-connector#1]
I am very sorry to spam this repository, but unfortunately, I cannot create an issue at https://github.com/timroemisch/cul -- I can see that you wrote the FHT implementation for the CUL/Node.js project and I would like to ask a question about it.

In your implementation the message is interpreted as follows:

`TAAAACCXXVV`

Where T is ignored, AAAA (i.e. slice(1,5)) is address, CC (i.e. slice(5,7)) is command and VV (i.e. slice(9,11)) is value. The interpretation of value depends on command, this is very clear and easy to read. My question is about two bytes XX (slice(7,9)). Do you have an idea what are they for?

I believe that if the command is 00-08 (i.e an actual actuator), these two bytes contain instructions for the valve. Looking over the net, I see various versions of this document: http://fhz4linux.info/tiki-index.php?page=FHT+protocol that parse these two bytes, however not all values have known meanings, and some values have different meaning from what I am observing.

Do you have some insight into the meaning of the bytes 7 and 8? I would be very grateful for any information. Thank you and again, I apologize for posting a bug in different repo.

Cheers,
Martin

**Comment by timroemisch** [comment]
hi,
I hope your question is still relevant, i haven't got any notifications that you wrote this issue...

I used the [command reference](http://culfw.de/commandref.html#cmd_T) on the culfw page to implement the fht functionality.

It's been a long time since I read the commandref but it looks like it's the FHT8v syntax.

I haven't tried anything with these two Bytes but it would be really interesting if these are for controlling actuators.

I hope i could help you
Tim
