### ISSUE TITLE
Release version tagging missing

### ISSUE THREAD

**Issue by matthew-larner** [timroemisch/mqtt-s7-connector#11]
Hi,

Great work on this project. I would really appreciate it if you could tag release versions and carry this through to the docker hub builds. Without this, every release gets tagged with 'latest' which is not good practice.

Thanks!

**Comment by timroemisch** [comment]
Hi,

I appreciate your suggestion.  
Since the project is relatively small, I haven't implemented tagging release versions for Docker Hub builds in the CI setup, which is built with the GitLab CI on my private instance. 
However, if you're interested, you can create a pull request with the feature, 
and I would be happy to review and merge it.
